mindmap
  root((仓颉
  面向对象))
    封装
      类和对象
        class
        实例化
        成员变量
        成员函数
          this关键字
          重载
        构造函数
          普通构造函数
            重载
            无参默认构造
          主构造函数
            成员参数变量
        静态成员
          静态成员变量
            类级别共享
          静态成员函数
            类级别调用
        属性
          mut
          get函数
          set函数
          private
      可见性修饰符
        public
        protected
        private

    继承
      类的继承
        单继承
        父类
        子类
      重写
        父类成员
      可见性修饰符
        public
        protected
        private
      单例类
        私有构造函数
        静态实例变量
        getInstance
    多态
      通过继承和重写实现
        向上转型
        向下转型
        is操作符
      抽象类
        不能直接实例化
        抽象方法
        具体方法
      接口
        定义方法签名
        类实现接口
